export const GET_BUYING_INQUIRY_REQUEST = "GET_BUYING_INQUIRY_REQUEST";
export const GET_BUYING_INQUIRY_SUCCESS = "GET_BUYING_INQUIRY_SUCCESS";
export const GET_BUYING_INQUIRY_FAIL = "GET_BUYING_INQUIRY_FAIL";

export const DELETE_BUYING_INQUIRY_SUCCESS = "DELETE_BUYING_INQUIRY_SUCCESS";
export const DELETE_BUYING_INQUIRY_FAIL = "DELETE_BUYING_INQUIRY_FAIL";
export const DELETE_BUYING_INQUIRY_RESET = "DELETE_BUYING_INQUIRY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
