export const GET_NEWSLETTER_REQUEST = "GET_NEWSLETTER_REQUEST";
export const GET_NEWSLETTER_SUCCESS = "GET_NEWSLETTER_SUCCESS";
export const GET_NEWSLETTER_FAIL = "GET_NEWSLETTER_FAIL";

export const DELETE_NEWSLETTER_SUCCESS = "DELETE_NEWSLETTER_SUCCESS";
export const DELETE_NEWSLETTER_FAIL = "DELETE_NEWSLETTER_FAIL";
export const DELETE_NEWSLETTER_RESET = "DELETE_NEWSLETTER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
