export const REGISTER_PROMO_REQUEST = "REGISTER_PROMO_REQUEST";
export const REGISTER_PROMO_SUCCESS = "REGISTER_PROMO_SUCCESS";
export const REGISTER_PROMO_FAIL = "REGISTER_PROMO_FAIL";
export const REGISTER_PROMO_RESET = "REGISTER_PROMO_RESET";

export const GET_PROMOS_REQUEST = "GET_PROMOS_REQUEST";
export const GET_PROMOS_SUCCESS = "GET_PROMOS_SUCCESS";
export const GET_PROMOS_FAIL = "GET_PROMOS_FAIL";

export const DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS";
export const DELETE_PROMO_FAIL = "DELETE_PROMO_FAIL";
export const DELETE_PROMO_RESET = "DELETE_PROMO_RESET";

export const UPDATE_PROMO_REQUEST = "UPDATE_PROMO_REQUEST";
export const UPDATE_PROMO_SUCCESS = "UPDATE_PROMO_SUCCESS";
export const UPDATE_PROMO_FAIL = "UPDATE_PROMO_FAIL";
export const UPDATE_PROMO_RESET = "UPDATE_PROMO_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
