export const ADD_PROPERTY_REQUEST = "ADD_PROPERTY_REQUEST";
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const ADD_PROPERTY_FAIL = "ADD_PROPERTY_FAIL";
export const ADD_PROPERTY_RESET = "ADD_PROPERTY_RESET";

export const GET_PROPERTY_REQUEST = "GET_PROPERTY_REQUEST";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const GET_PROPERTY_FAIL = "GET_PROPERTY_FAIL";

export const GET_SINGLE_PROPERTY_REQUEST = "GET_SINGLE_PROPERTY_REQUEST";
export const GET_SINGLE_PROPERTY_SUCCESS = "GET_SINGLE_PROPERTY_SUCCESS";
export const GET_SINGLE_PROPERTY_FAIL = "GET_SINGLE_PROPERTY_FAIL";

export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAIL = "DELETE_PROPERTY_FAIL";
export const DELETE_PROPERTY_RESET = "DELETE_PROPERTY_RESET";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAIL = "UPDATE_PROPERTY_FAIL";
export const UPDATE_PROPERTY_RESET = "UPDATE_PROPERTY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
