export const GET_SELLING_INQUIRY_REQUEST = "GET_SELLING_INQUIRY_REQUEST";
export const GET_SELLING_INQUIRY_SUCCESS = "GET_SELLING_INQUIRY_SUCCESS";
export const GET_SELLING_INQUIRY_FAIL = "GET_SELLING_INQUIRY_FAIL";

export const DELETE_SELLING_INQUIRY_SUCCESS = "DELETE_SELLING_INQUIRY_SUCCESS";
export const DELETE_SELLING_INQUIRY_FAIL = "DELETE_SELLING_INQUIRY_FAIL";
export const DELETE_SELLING_INQUIRY_RESET = "DELETE_SELLING_INQUIRY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
