export const REGISTER_SHORT_VIDEO_REQUEST = "REGISTER_SHORT_VIDEO_REQUEST";
export const REGISTER_SHORT_VIDEO_SUCCESS = "REGISTER_SHORT_VIDEO_SUCCESS";
export const REGISTER_SHORT_VIDEO_FAIL = "REGISTER_SHORT_VIDEO_FAIL";
export const REGISTER_SHORT_VIDEO_RESET = "REGISTER_SHORT_VIDEO_RESET";

export const GET_SHORT_VIDEOS_REQUEST = "GET_SHORT_VIDEOS_REQUEST";
export const GET_SHORT_VIDEOS_SUCCESS = "GET_SHORT_VIDEOS_SUCCESS";
export const GET_SHORT_VIDEOS_FAIL = "GET_SHORT_VIDEOS_FAIL";

export const DELETE_SHORT_VIDEO_SUCCESS = "DELETE_SHORT_VIDEO_SUCCESS";
export const DELETE_SHORT_VIDEO_FAIL = "DELETE_SHORT_VIDEO_FAIL";
export const DELETE_SHORT_VIDEO_RESET = "DELETE_SHORT_VIDEO_RESET";

export const UPDATE_SHORT_VIDEO_REQUEST = "UPDATE_SHORT_VIDEO_REQUEST";
export const UPDATE_SHORT_VIDEO_SUCCESS = "UPDATE_SHORT_VIDEO_SUCCESS";
export const UPDATE_SHORT_VIDEO_FAIL = "UPDATE_SHORT_VIDEO_FAIL";
export const UPDATE_SHORT_VIDEO_RESET = "UPDATE_SHORT_VIDEO_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
