export const ADD_TESTIMONIAL_REQUEST = "ADD_TESTIMONIAL_REQUEST";
export const ADD_TESTIMONIAL_SUCCESS = "ADD_TESTIMONIAL_SUCCESS";
export const ADD_TESTIMONIAL_FAIL = "ADD_TESTIMONIAL_FAIL";
export const ADD_TESTIMONIAL_RESET = "ADD_TESTIMONIAL_RESET";

export const GET_TESTIMONIAL_REQUEST = "GET_TESTIMONIAL_REQUEST";
export const GET_TESTIMONIAL_SUCCESS = "GET_TESTIMONIAL_SUCCESS";
export const GET_TESTIMONIAL_FAIL = "GET_TESTIMONIAL_FAIL";

export const DELETE_TESTIMONIAL_SUCCESS = "DELETE_TESTIMONIAL_SUCCESS";
export const DELETE_TESTIMONIAL_FAIL = "DELETE_TESTIMONIAL_FAIL";
export const DELETE_TESTIMONIAL_RESET = "DELETE_TESTIMONIAL_RESET";

export const UPDATE_TESTIMONIAL_REQUEST = "UPDATE_TESTIMONIAL_REQUEST";
export const UPDATE_TESTIMONIAL_SUCCESS = "UPDATE_TESTIMONIAL_SUCCESS";
export const UPDATE_TESTIMONIAL_FAIL = "UPDATE_TESTIMONIAL_FAIL";
export const UPDATE_TESTIMONIAL_RESET = "UPDATE_TESTIMONIAL_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
