export const GET_PROPERTY_REQUEST = "GET_PROPERTY_REQUEST";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const GET_PROPERTY_FAIL = "GET_PROPERTY_FAIL";

export const GET_SINGLE_PROPERTY_REQUEST = "GET_SINGLE_PROPERTY_REQUEST";
export const GET_SINGLE_PROPERTY_SUCCESS = "GET_SINGLE_PROPERTY_SUCCESS";
export const GET_SINGLE_PROPERTY_FAIL = "GET_SINGLE_PROPERTY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
