export const GET_TESTIMONIAL_REQUEST = "GET_TESTIMONIAL_REQUEST";
export const GET_TESTIMONIAL_SUCCESS = "GET_TESTIMONIAL_SUCCESS";
export const GET_TESTIMONIAL_FAIL = "GET_TESTIMONIAL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
